### PR TITLE
Migrate to Typescript

### PR DESCRIPTION
**Pull request by pierpo**
I just migrated the whole codebase to Typescript.

## Benefits

- Typescript is way more adopted right now and people will be more likely to contribute
- Flow was quite a struggle when it came to upgrading versions. It should be easier with Typescript now.
- DevX is probably better (I haven't checked recent flow versions though)
- `.d.ts` generation is now automated

## Drawbacks

- Because of the automatic `.d.ts` generation, this is dropping flow-types support.

## TODO

- [x] It should work, but I need to properly test on an external project that everything still works (runtime + type definitions)

### CODE REVIEW

**Comment by pierpo** [comment]
Everything works! :rocket:

**Comment by pierpo** [comment]
Sure, will do!

**Comment by pierpo** [comment]
Done. Thanks for asking for it. I was procrastinating :smile: (and also wondering "major or minor?" but since there's been a drop in flow support, it can be considered a major upgrade)

**Comment by ThiloAschebrock** [comment]
Thank you! @pierpo

**Pull request merged**
