### PR TITLE
support shortest path layout between anchors

### PR DESCRIPTION
**Pull request by marcocheungkami**
Referring to #119

### CODE REVIEW

**Comment by pierpo** [comment]
Thank you for the PR! It looks like it does the job :blush: 

I'll have a deeper look in the coming days. Thanks!

**Comment by pierpo** [comment]
So, I had a look. Unfortunately, it does not work properly yet:

- The code does not run. You forgot to declare the shortestPath argument in other places.

- The API is not satisfying, unfortunately. We have two booleans "noCurves", "shortestPath"... But having "noCurves" to "false" and "shortestPath" to "true" does not really make sense. My point is that we should probably have a "drawingMode" props that has multiple states: "shortest-path", "curves", "no-curves" (needs to be thought properly, this is just an idea)

- Even when the above is fixed, there is an offset once the arrow is drawn. Indeed, the path of the arrow isn't as obvious as we think it should be: the arrowhead has some logic to be drawn. We have to draw a line from the start to the beginning minus the arrowhead length (because it is not included in the path). Here the offset on the left element corresponds as the arrowhead height that has been substracted to the top anchor. image

I'm afraid this issue is more complex than it looks like :disappointed: 
The drawing logic needs a deeper work.

**Comment by marcocheungkami** [comment]
I see. There is an offset problem needed to be fixed among vertical linkages. Alright, I may try to fix this issue in the coming days.

**Comment by marcocheungkami** [comment]
@pierpo I have modified the logic and seems there won't be any extra spacing.

image

**Comment by pierpo** [comment]
Thank you for the updates :blush: 
And sorry for not coming back earlier!

So, it's better indeed, thanks for handling this. But I don't think it's in a mergeable state, because it's still not looking perfect. The fact that the arrow is angled in the end is not really what one would expect :cry: 

I made a little drawing of what's necessary. It's way more complex:

image

With the `theta` angle being `atan2(xe - xa, ye  ya)`

There's no such mechanism in the lib yet :grimacing:

**Comment by pierpo** [comment]
Closed in favor of https://github.com/pierpo/react-archer/pull/135 :blush:

**Pull request closed without merging**
